### PR TITLE
added dark mode

### PR DESCRIPTION
**Pull request by raviikushh**
The changes that has been made are -

-Added the dark theme to the whole page
-made changes in the navbar by using buttons and hover effect
-made changes in the download cards using flex wrap and hover effects
-By clicking on the feature in the navbar it will smoothly scroll down to feature part
-
Screenshot (218)
Screenshot (219)
made few changes in the footer too
Screenshot (220)
Screenshot (222)
Screenshot (223)

### CODE REVIEW

**Comment by justEhmadSaeed** [comment]
Hi @raviikushh, 
Sorry that I had to update the project settings, which hindered the automated deployment on Vercel.
Can you update your PR accordingly?

**Comment by raviikushh** [comment]
Yeahh sure..

**Comment by raviikushh** [comment]
> Hi @raviikushh, 
> Sorry that I had to update the project settings, which hindered the automated deployment on Vercel.
> Can you update your PR accordingly?

Just tell me when I need to PR again...

**Comment by justEhmadSaeed** [comment]
> Just tell me when I need to PR again...

I have already merged the changes to the master. You can submit now.

**Comment by raviikushh** [comment]
> > Just tell me when I need to PR again...
> 
> I have already merged the changes to the master. You can submit now.

Ok I'll submit it

**Comment by raviikushh** [comment]
> > Just tell me when I need to PR again...
> 
> I have already merged the changes to the master. You can submit now.

where to Submit ...? I mean do I need to PR again?

**Comment by justEhmadSaeed** [comment]
Hi @raviikushh, you have to resolve the merge conflicts for your PR to be merged. 
up to you how you want to do it.

**Comment by raviikushh** [comment]
> Hi @raviikushh, you have to resolve the merge conflicts for your PR to be merged. 
> up to you how you want to do it.

Okay..
I'll figure out.

**Comment by raviikushh** [comment]
> Hi @raviikushh, you have to resolve the merge conflicts for your PR to be merged. 
> up to you how you want to do it.

It's done ✅

**Comment by raviikushh** [comment]
>You can merge now.

**Comment by justEhmadSaeed** [comment]
@raviikushh please keep the original theme by default.
The dark theme requires some improvements, which can be done later, so the default should be the previous white theme.

**Comment by raviikushh** [comment]
> @raviikushh please keep the original theme by default.
> The dark theme requires some improvements, which can be done later, so the default should be the previous white theme.

Okay, let me check I'll fix it.

**Comment by raviikushh** [comment]
> @raviikushh please keep the original theme by default.
> The dark theme requires some improvements, which can be done later, so the default should be the previous white theme.

It's Done ✅

**Comment by justEhmadSaeed** [comment]
@raviikushh I'm having issues merging your PR, feels like you haven't taken a fresh pull from the main branch.
Try to follow these steps:
````
# Fork sync your repo with this repo
# and then:
git reset HEAD~3 --soft
git stash
# Merge the main branch into your feature branch and resolve conflicts if any
git stash pop
````
And then commit your changes and force push the commits.

**Comment by raviikushh** [comment]
> @raviikushh I'm having issues merging your PR, feels like you haven't taken a fresh pull from the main branch.
> Try to follow these steps:
> ````
> # Fork sync your repo with this repo
> # and then:
> git reset HEAD~3 --soft
> git stash
> # Merge the main branch into your feature branch and resolve conflicts if any
> git stash pop
> ````
> And then commit your changes and force push the commits.

Ok I'll do it.
But previous conflict was already resolved then what's the issue it is showing...?

**Comment by justEhmadSaeed** [comment]
> Ok I'll do it. But previous conflict was already resolved then what's the issue it is showing...?

there were changes in the .gitignore file which are not being reflected in your PR.

**Comment by raviikushh** [comment]
> > Ok I'll do it. But previous conflict was already resolved then what's the issue it is showing...?
> 
> there were changes in the .gitignore file which are not being reflected in your PR.

Okay I'll make changes in my file too

**Comment by raviikushh** [comment]
> > Ok I'll do it. But previous conflict was already resolved then what's the issue it is showing...?
> 
> there were changes in the .gitignore file which are not being reflected in your PR.

Fixed it. Try to merge now

**Comment by justEhmadSaeed** [comment]
@raviikushh I'm sorry but it looks like you're not following the instructions/ basic git flow and trying to recreate the `main` branch files.
A better approach would be to reset your commits (not your changes) and then merge the main branch into yours.

**Comment by raviikushh** [comment]
Okay

**Comment by raviikushh** [comment]
i have synced the PR with the latest main , can you please recheck and merge the PR

**Comment by justEhmadSaeed** [comment]
> @raviikushh I'm having issues merging your PR, feels like you haven't taken a fresh pull from the main branch. Try to follow these steps:
> 
> ```
> # Fork sync your repo with this repo
> # and then reset all your commits to make a new single & clean commit:
> # 3 can be replaced by the number of your own commits.
> git reset HEAD~3 --soft
> git stash
> # Merge the main branch into your feature branch and resolve conflicts if any
> git stash pop
> ```
> 
> And then commit your changes and force push the commits.

Please follow the instructions to clean the PR.
And if it's not doable for you, you can copy your changes to make a new PR with a fresh fork.

**Comment by raviikushh** [comment]
> > @raviikushh I'm having issues merging your PR, feels like you haven't taken a fresh pull from the main branch. Try to follow these steps:
> > ```
> > # Fork sync your repo with this repo
> > # and then reset all your commits to make a new single & clean commit:
> > # 3 can be replaced by the number of your own commits.
> > git reset HEAD~3 --soft
> > git stash
> > # Merge the main branch into your feature branch and resolve conflicts if any
> > git stash pop
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then commit your changes and force push the commits.
> 
> Please follow the instructions to clean the PR. And if it's not doable for you, you can copy your changes to make a new PR with a fresh fork.

I did Exactly what you told. Now please recheck and try to merge again

**Comment by raviikushh** [comment]
> > @raviikushh I'm having issues merging your PR, feels like you haven't taken a fresh pull from the main branch. Try to follow these steps:
> > 
> > ```
> > # Fork sync your repo with this repo
> > # and then reset all your commits to make a new single & clean commit:
> > # 3 can be replaced by the number of your own commits.
> > git reset HEAD~3 --soft
> > git stash
> > # Merge the main branch into your feature branch and resolve conflicts if any
> > git stash pop
> > ```
> > 
> > And then commit your changes and force push the commits.
> 
> Please follow the instructions to clean the PR.
> And if it's not doable for you, you can copy your changes to make a new PR with a fresh fork.

Can you please recheck and try to merge now....
I've synced the branch and followed all the steps you told.

**Comment by raviikushh** [comment]
Can you please check it for one last time and merge.

**Pull request merged**
